const quizData = [
    // ----------------------------------------------------------------------
    // EUROPA (30 DOMANDE) - ID 1 a 30
    // ----------------------------------------------------------------------
    { id: 1, categoria: "Europa", testo: "Il bianco nella bandiera della Russia simboleggia la pace e la purezza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "RU" },
    { id: 2, categoria: "Europa", testo: "Le tre strisce orizzontali della bandiera dell'Italia rappresentano i tre rami del governo.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "IT" },
    { id: 3, categoria: "Europa", testo: "La croce bianca nella bandiera della Svizzera simboleggia l'unità e la democrazia.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CH" },
    { id: 4, categoria: "Europa", testo: "Il giallo nella bandiera della Spagna rappresenta la ricchezza mineraria del Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "ES" },
    { id: 5, categoria: "Europa", testo: "Il blu nella bandiera della Grecia rappresenta il Mar Egeo e il cielo.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "GR" },
    { id: 6, categoria: "Europa", testo: "La bandiera della Germania utilizza i colori nero, rosso e giallo che simboleggiano l'unità del Paese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "DE" },
    { id: 7, categoria: "Europa", testo: "Le dodici stelle nella bandiera dell'Unione Europea simboleggiano i dodici stati fondatori.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "EU" }, // Codice speciale per l'UE
    { id: 8, categoria: "Europa", testo: "Il verde nella bandiera dell'Irlanda rappresenta la tradizione repubblicana e cattolica.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "IE" },
    { id: 9, categoria: "Europa", testo: "La bandiera della Francia, il tricolore, fu adottata dopo la Rivoluzione Francese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "FR" },
    { id: 10, categoria: "Europa", testo: "Il blu scuro nella bandiera del Regno Unito (Union Jack) simboleggia la Scozia.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "GB" },
    { id: 11, categoria: "Europa", testo: "L'aquila bicipite sulla bandiera dell'Albania è un riferimento all'Impero Romano.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "AL" },
    { id: 12, categoria: "Europa", testo: "Il rosso della bandiera del Portogallo è il colore della gioia e del buon auspicio.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "PT" },
    { id: 13, categoria: "Europa", testo: "Il giallo nella bandiera dell'Ucraina rappresenta i campi di grano del Paese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "UA" },
    { id: 14, categoria: "Europa", testo: "La bandiera del Belgio è un tricolore orizzontale.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "BE" },
    { id: 15, categoria: "Europa", testo: "Il rosso nella bandiera della Turchia deriva dalla mezzaluna e stella del periodo ottomano.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "TR" },
    { id: 16, categoria: "Europa", testo: "Il drago nella bandiera del Galles (non-Union Jack) è conosciuto come Y Ddraig Goch.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "GB-WLS" }, // ISO per il Galles (se supportato, altrimenti GB)
    { id: 17, categoria: "Europa", testo: "La bandiera dell'Austria è identica a quella della Lettonia ma con una tonalità di rosso diversa.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "AT" },
    { id: 18, categoria: "Europa", testo: "Il blu nella bandiera della Svezia simboleggia i laghi e il cielo.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "SE" },
    { id: 19, categoria: "Europa", testo: "La bandiera della Polonia, bianca e rossa, simboleggia la neve e il cielo.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "PL" },
    { id: 20, categoria: "Europa", testo: "Il sole nella bandiera della Macedonia del Nord simboleggia il Sole di Vergina, un antico simbolo macedone.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "MK" },
    { id: 21, categoria: "Europa", testo: "La croce scandinava sulla bandiera della Danimarca simboleggia l'Impero Danese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "DK" },
    { id: 22, categoria: "Europa", testo: "Il verde nella bandiera dell'Ungheria rappresenta le foreste del Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "HU" },
    { id: 23, categoria: "Europa", testo: "Le stelle nella bandiera della Bosnia ed Erzegovina sono tutte orientate verticalmente.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "BA" },
    { id: 24, categoria: "Europa", testo: "Il bianco nella bandiera della Croazia è un riferimento alla dinastia Trpimirović.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "HR" },
    { id: 25, categoria: "Europa", testo: "La bandiera dell'Estonia (blu-nero-bianco) fu adottata dopo l'indipendenza dall'Unione Sovietica.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "EE" },
    { id: 26, categoria: "Europa", testo: "La bandiera della Lituania ha i colori giallo, verde e rosso che rappresentano il sole, la speranza e il coraggio.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "LT" },
    { id: 27, categoria: "Europa", testo: "La bandiera dell'Islanda presenta gli stessi colori del tricolore francese, ma in una disposizione diversa.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "IS" },
    { id: 28, categoria: "Europa", testo: "La bandiera della Norvegia condivide la stessa croce scandinava di tutte le altre nazioni nordiche.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "NO" },
    { id: 29, categoria: "Europa", testo: "Il leone rampante nella bandiera della Repubblica Ceca simboleggia la forza e il coraggio.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CZ" },
    { id: 30, categoria: "Europa", testo: "La bandiera della Romania ha un disegno identico a quello della Moldavia, ma senza lo stemma centrale.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "RO" },

    // ----------------------------------------------------------------------
    // ASIA (30 DOMANDE) - ID 31 a 60
    // ----------------------------------------------------------------------
    { id: 31, categoria: "Asia", testo: "Il cerchio rosso nella bandiera del Giappone simboleggia la luna piena.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "JP" },
    { id: 32, categoria: "Asia", testo: "La bandiera della Cina presenta una grande stella che simboleggia il Partito Comunista Cinese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "CN" },
    { id: 33, categoria: "Asia", testo: "I colori nero, bianco, verde e rosso nella bandiera della Palestina sono colori panarabi.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "PS" },
    { id: 34, categoria: "Asia", testo: "Il verde nella bandiera dell'Arabia Saudita rappresenta la fertilità e la ricchezza agricola.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "SA" },
    { id: 35, categoria: "Asia", testo: "Le tre strisce verticali della bandiera dell'India rappresentano tre diversi gruppi etnici.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "IN" },
    { id: 36, categoria: "Asia", testo: "La bandiera dell'Israele, con la Stella di David, fu creata durante il Mandato Britannico.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "IL" },
    { id: 37, categoria: "Asia", testo: "L'albero di cedro nella bandiera del Libano simboleggia la longevità e la forza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "LB" },
    { id: 38, categoria: "Asia", testo: "Il blu nella bandiera della Corea del Sud rappresenta l'equilibrio tra lo Yin e lo Yang.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "KR" },
    { id: 39, categoria: "Asia", testo: "La bandiera dell'Indonesia è identica a quella della Polonia, ma con i colori invertiti.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "ID" },
    { id: 40, categoria: "Asia", testo: "La stella a quattordici punte nella bandiera della Malaysia simboleggia le sue tredici regioni e il governo federale.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "MY" },
    { id: 41, categoria: "Asia", testo: "Il rosso nella bandiera del Vietnam simboleggia il sangue versato per l'indipendenza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "VN" },
    { id: 42, categoria: "Asia", testo: "La bandiera delle Filippine, quando la nazione è in guerra, viene issata con la striscia blu in alto.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "PH" },
    { id: 43, categoria: "Asia", testo: "Il sole nella bandiera dell'Afghanistan è circondato da una corona di alloro.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "AF" },
    { id: 44, categoria: "Asia", testo: "La bandiera dell'Iraq presenta una scritta in Kufic che significa 'Dio è grande'.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "IQ" },
    { id: 45, categoria: "Asia", testo: "Le tre stelle nella bandiera della Siria rappresentano i tre quarti della popolazione del Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "SY" },
    { id: 46, categoria: "Asia", testo: "La bandiera del Nepal è l'unica al mondo a non essere rettangolare.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "NP" },
    { id: 47, categoria: "Asia", testo: "I colori della bandiera dell'India (zafferano, bianco, verde) sono noti come Tiranga.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "IN" },
    { id: 48, categoria: "Asia", testo: "Il bianco nella bandiera del Qatar rappresenta la pace e la neutralità.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "QA" },
    { id: 49, categoria: "Asia", testo: "Il rosso nella bandiera dell'Oman simboleggia le battaglie combattute per l'indipendenza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "OM" },
    { id: 50, categoria: "Asia", testo: "La bandiera della Corea del Nord è conosciuta come Inmin'gi.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "KP" },
    { id: 51, categoria: "Asia", testo: "La bandiera del Laos presenta un cerchio bianco centrale che simboleggia la luna piena sopra il fiume Mekong.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "LA" },
    { id: 52, categoria: "Asia", testo: "L'elemento centrale nella bandiera del Kazakistan è un cammello dorato.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "KZ" },
    { id: 53, categoria: "Asia", testo: "Il blu nella bandiera dell'Uzbekistan rappresenta il cielo e l'acqua, fonti di vita.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "UZ" },
    { id: 54, categoria: "Asia", testo: "La bandiera del Turkmenistan presenta cinque tappeti (gül) che simboleggiano le cinque province del Paese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "TM" },
    { id: 55, categoria: "Asia", testo: "Il cerchio blu nella bandiera del Bangladesh rappresenta l'acqua e l'unità.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "BD" },
    { id: 56, categoria: "Asia", testo: "La bandiera del Pakistan presenta una striscia bianca che simboleggia le minoranze religiose.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "PK" },
    { id: 57, categoria: "Asia", testo: "L'uccello nella bandiera dell'Egitto è l'aquila di Saladino.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "EG" },
    { id: 58, categoria: "Asia", testo: "La bandiera della Giordania ha un triangolo nero sul lato dell'asta.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "JO" },
    { id: 59, categoria: "Asia", testo: "La bandiera del Kuwait presenta i colori panarabi in un disegno a tre strisce orizzontali e un trapezio nero.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "KW" },
    { id: 60, categoria: "Asia", testo: "Il rosso nella bandiera della Thailandia rappresenta la monarchia.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "TH" },

    // ----------------------------------------------------------------------
    // AMERICA (30 DOMANDE) - ID 61 a 90
    // ----------------------------------------------------------------------
    { id: 61, categoria: "America", testo: "Le 50 stelle nella bandiera degli Stati Uniti d'America rappresentano le 50 capitali dei 50 Stati.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "US" },
    { id: 62, categoria: "America", testo: "La bandiera del Canada presenta una foglia d'acero a quindici punte che simboleggia le sue quindici province.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CA" },
    { id: 63, categoria: "America", testo: "Il blu nella bandiera del Messico simboleggia la speranza e la religione cattolica.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "MX" },
    { id: 64, categoria: "America", testo: "Lo stemma centrale della bandiera del Messico raffigura un'aquila che divora un serpente su un cactus.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "MX" },
    { id: 65, categoria: "America", testo: "La bandiera del Brasile presenta una scritta che in portoghese significa 'Ordine e Progresso'.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "BR" },
    { id: 66, categoria: "America", testo: "Il sole (Sol de Mayo) nella bandiera dell'Argentina simboleggia la dichiarazione di indipendenza del Paese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "AR" },
    { id: 67, categoria: "America", testo: "Il rosso nella bandiera del Cile rappresenta il sangue versato per l'indipendenza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "CL" },
    { id: 68, categoria: "America", testo: "La bandiera della Colombia ha la banda rossa più larga delle altre due (giallo e blu).", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CO" },
    { id: 69, categoria: "America", testo: "Il blu e il bianco nella bandiera dell'Uruguay rappresentano il Mar dei Caraibi e le spiagge.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "UY" },
    { id: 70, categoria: "America", testo: "La bandiera del Perù presenta una striscia bianca che simboleggia la pace e la giustizia.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "PE" },
    { id: 71, categoria: "America", testo: "La bandiera della Bolivia ha tre strisce orizzontali in ordine rosso, giallo e verde.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "BO" },
    { id: 72, categoria: "America", testo: "La bandiera del Paraguay presenta lo stesso emblema sul fronte e sul retro.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "PY" },
    { id: 73, categoria: "America", testo: "Le cinque stelle della bandiera dell'Honduras rappresentano le cinque nazioni degli Stati Uniti dell'America Centrale.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "HN" },
    { id: 74, categoria: "America", testo: "Il blu nella bandiera del Venezuela simboleggia i mari e gli oceani che circondano il Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "VE" },
    { id: 75, categoria: "America", testo: "Il triangolo nella bandiera di Cuba simboleggia la parità e l'uguaglianza.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CU" },
    { id: 76, categoria: "America", testo: "Il leone nella bandiera della Giamaica simboleggia la forza e il coraggio della popolazione.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "JM" },
    { id: 77, categoria: "America", testo: "La bandiera della Repubblica Dominicana è l'unica al mondo a presentare una Bibbia aperta.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "DO" },
    { id: 78, categoria: "America", testo: "Le due stelle sulla bandiera di Panama simboleggiano i due partiti politici del Paese.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "PA" },
    { id: 79, categoria: "America", testo: "Il rosso nella bandiera del Nicaragua simboleggia il sangue versato per l'indipendenza.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "NI" },
    { id: 80, categoria: "America", testo: "La bandiera di Haiti è un bicolore verticale rosso e blu.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "HT" },
    { id: 81, categoria: "America", testo: "Il verde nella bandiera dell'Ecuador rappresenta la ricchezza delle sue foreste.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "EC" },
    { id: 82, categoria: "America", testo: "La bandiera dell'El Salvador presenta lo stemma nazionale con un triangolo equilatero.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "SV" },
    { id: 83, categoria: "America", testo: "Le tre strisce blu nella bandiera del Guatemala simboleggiano i due oceani che circondano il Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "GT" },
    { id: 84, categoria: "America", testo: "La bandiera della Costa Rica ha una banda centrale rossa più larga.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "CR" },
    { id: 85, categoria: "America", testo: "Il blu nella bandiera di Porto Rico (territorio USA) simboleggia il cielo.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "PR" },
    { id: 86, categoria: "America", testo: "La bandiera del Belize è l'unica bandiera nazionale con 12 colori diversi.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "BZ" },
    { id: 87, categoria: "America", testo: "La bandiera del Messico è un bicolore orizzontale.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "MX" },
    { id: 88, categoria: "America", testo: "La bandiera del Venezuela presenta otto stelle che simboleggiano otto province.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "VE" },
    { id: 89, categoria: "America", testo: "La bandiera della Groenlandia (territorio danese) è identica a quella della Danimarca.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "GL" },
    { id: 90, categoria: "America", testo: "Il bianco nella bandiera del Canada simboleggia la neutralità e la pace.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "CA" },

    // ----------------------------------------------------------------------
    // ALTRI CONTINENTI (AFRICA & OCEANIA) (10 DOMANDE) - ID 91 a 100
    // ----------------------------------------------------------------------
    { id: 91, categoria: "Africa & Oceania", testo: "Il rosso, verde e blu nella bandiera del Sudafrica (Africa) simboleggiano le tre razze principali del Paese.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "ZA" },
    { id: 92, categoria: "Africa & Oceania", testo: "La bandiera dell'Etiopia (Africa) presenta un pentagramma centrale che simboleggia l'unità e la diversità del popolo.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "ET" },
    { id: 93, categoria: "Africa & Oceania", testo: "La stella nella bandiera dell'Australia (Oceania) è la Stella Polare, usata per la navigazione.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "AU" },
    { id: 94, categoria: "Africa & Oceania", testo: "La bandiera della Nuova Zelanda (Oceania) è identica a quella dell'Australia, a parte il numero di stelle.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "NZ" },
    { id: 95, categoria: "Africa & Oceania", testo: "La bandiera del Kenya (Africa) presenta uno scudo Masai che simboleggia la difesa della libertà.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "KE" },
    { id: 96, categoria: "Africa & Oceania", testo: "Il nero nella bandiera dell'Egitto (Africa) rappresenta l'oscuro passato dell'oppressione.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "EG" },
    { id: 97, categoria: "Africa & Oceania", testo: "Il rosso nella bandiera della Cina (Asia) simboleggia la gioia e la felicità.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "CN" },
    { id: 98, categoria: "Africa & Oceania", testo: "La bandiera della Tunisia (Africa) è un cerchio rosso con una stella e una mezzaluna all'interno.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "TN" },
    { id: 99, categoria: "Africa & Oceania", testo: "Il blu della bandiera di Figi (Oceania) simboleggia l'Oceano Pacifico.", opzioni: ["Vero", "Falso"], corretta: "Vero", isoCode: "FJ" },
    { id: 100, categoria: "Africa & Oceania", testo: "La bandiera del Marocco (Africa) presenta una stella a sei punte verde chiamata 'Sigillo di Salomone'.", opzioni: ["Vero", "Falso"], corretta: "Falso", isoCode: "MA" }
];