const quizData = [
    // ----------------------------------------------------------------------
    // EUROPE (30 QUESTIONS) - ID 1 to 30
    // ----------------------------------------------------------------------
    { id: 1, categoria: "Europe", testo: "The white in the Russian flag symbolizes peace and purity.", opzioni: ["True", "False"], corretta: "True", isoCode: "RU" },
    { id: 2, categoria: "Europe", testo: "The three horizontal stripes of the Italian flag represent the three branches of government.", opzioni: ["True", "False"], corretta: "False", isoCode: "IT" },
    { id: 3, categoria: "Europe", testo: "The white cross on the Swiss flag symbolizes unity and democracy.", opzioni: ["True", "False"], corretta: "False", isoCode: "CH" },
    { id: 4, categoria: "Europe", testo: "The yellow in the Spanish flag represents the country's mineral wealth.", opzioni: ["True", "False"], corretta: "False", isoCode: "ES" },
    { id: 5, categoria: "Europe", testo: "The blue in the Greek flag represents the Aegean Sea and the sky.", opzioni: ["True", "False"], corretta: "True", isoCode: "GR" },
    { id: 6, categoria: "Europe", testo: "The German flag uses the colors black, red, and gold to symbolize the unity of the country.", opzioni: ["True", "False"], corretta: "True", isoCode: "DE" },
    { id: 7, categoria: "Europe", testo: "The twelve stars on the European Union flag symbolize the twelve founding states.", opzioni: ["True", "False"], corretta: "False", isoCode: "EU" },
    { id: 8, categoria: "Europe", testo: "The green in the Irish flag represents the republican and Catholic tradition.", opzioni: ["True", "False"], corretta: "False", isoCode: "IE" },
    { id: 9, categoria: "Europe", testo: "The French flag, the Tricolore, was adopted after the French Revolution.", opzioni: ["True", "False"], corretta: "True", isoCode: "FR" },
    { id: 10, categoria: "Europe", testo: "The dark blue in the United Kingdom flag (Union Jack) symbolizes Scotland.", opzioni: ["True", "False"], corretta: "True", isoCode: "GB" },
    { id: 11, categoria: "Europe", testo: "The double-headed eagle on the Albanian flag is a reference to the Roman Empire.", opzioni: ["True", "False"], corretta: "False", isoCode: "AL" },
    { id: 12, categoria: "Europe", testo: "The red in the Portuguese flag is the color of joy and good fortune.", opzioni: ["True", "False"], corretta: "False", isoCode: "PT" },
    { id: 13, categoria: "Europe", testo: "The yellow in the Ukrainian flag represents the country's wheat fields.", opzioni: ["True", "False"], corretta: "True", isoCode: "UA" },
    { id: 14, categoria: "Europe", testo: "The Belgian flag is a horizontal tricolor.", opzioni: ["True", "False"], corretta: "False", isoCode: "BE" },
    { id: 15, categoria: "Europe", testo: "The red of the Turkish flag originates from the crescent and star of the Ottoman period.", opzioni: ["True", "False"], corretta: "True", isoCode: "TR" },
    { id: 16, categoria: "Europe", testo: "The dragon on the Welsh flag is known as Y Ddraig Goch.", opzioni: ["True", "False"], corretta: "True", isoCode: "GB-WLS" },
    { id: 17, categoria: "Europe", testo: "The flag of Austria is identical to that of Latvia but with a different shade of red.", opzioni: ["True", "False"], corretta: "False", isoCode: "AT" },
    { id: 18, categoria: "Europe", testo: "The blue in the Swedish flag symbolizes lakes and the sky.", opzioni: ["True", "False"], corretta: "True", isoCode: "SE" },
    { id: 19, categoria: "Europe", testo: "The Polish flag, white and red, symbolizes snow and the sky.", opzioni: ["True", "False"], corretta: "False", isoCode: "PL" },
    { id: 20, categoria: "Europe", testo: "The sun in the North Macedonian flag symbolizes the Vergina Sun, an ancient Macedonian symbol.", opzioni: ["True", "False"], corretta: "True", isoCode: "MK" },
    { id: 21, categoria: "Europe", testo: "The Scandinavian cross on the Danish flag symbolizes the Danish Empire.", opzioni: ["True", "False"], corretta: "False", isoCode: "DK" },
    { id: 22, categoria: "Europe", testo: "The green in the Hungarian flag represents the country's forests.", opzioni: ["True", "False"], corretta: "False", isoCode: "HU" },
    { id: 23, categoria: "Europe", testo: "The stars on the Bosnia and Herzegovina flag are all oriented vertically.", opzioni: ["True", "False"], corretta: "True", isoCode: "BA" },
    { id: 24, categoria: "Europe", testo: "The white in the Croatian flag is a reference to the Trpimirović dynasty.", opzioni: ["True", "False"], corretta: "False", isoCode: "HR" },
    { id: 25, categoria: "Europe", testo: "The Estonian flag (blue-black-white) was adopted after independence from the Soviet Union.", opzioni: ["True", "False"], corretta: "False", isoCode: "EE" },
    { id: 26, categoria: "Europe", testo: "The Lithuanian flag has the colors yellow, green, and red representing the sun, hope, and courage.", opzioni: ["True", "False"], corretta: "True", isoCode: "LT" },
    { id: 27, categoria: "Europe", testo: "The Icelandic flag features the same colors as the French tricolor, but in a different arrangement.", opzioni: ["True", "False"], corretta: "False", isoCode: "IS" },
    { id: 28, categoria: "Europe", testo: "The Norwegian flag shares the same Scandinavian cross as all other Nordic nations.", opzioni: ["True", "False"], corretta: "True", isoCode: "NO" },
    { id: 29, categoria: "Europe", testo: "The lion rampant on the Czech Republic flag symbolizes strength and courage.", opzioni: ["True", "False"], corretta: "False", isoCode: "CZ" },
    { id: 30, categoria: "Europe", testo: "The Romanian flag has an identical design to the Moldovan one, but without the central coat of arms.", opzioni: ["True", "False"], corretta: "True", isoCode: "RO" },

    // ----------------------------------------------------------------------
    // ASIA (30 QUESTIONS) - ID 31 to 60
    // ----------------------------------------------------------------------
    { id: 31, categoria: "Asia", testo: "The red circle on the Japanese flag symbolizes the full moon.", opzioni: ["True", "False"], corretta: "False", isoCode: "JP" },
    { id: 32, categoria: "Asia", testo: "The Chinese flag features a large star that symbolizes the Communist Party of China.", opzioni: ["True", "False"], corretta: "True", isoCode: "CN" },
    { id: 33, categoria: "Asia", testo: "The colors black, white, green, and red in the Palestinian flag are Pan-Arab colors.", opzioni: ["True", "False"], corretta: "True", isoCode: "PS" },
    { id: 34, categoria: "Asia", testo: "The green in the Saudi Arabian flag represents fertility and agricultural wealth.", opzioni: ["True", "False"], corretta: "False", isoCode: "SA" },
    { id: 35, categoria: "Asia", testo: "The three vertical stripes of the Indian flag represent three different ethnic groups.", opzioni: ["True", "False"], corretta: "False", isoCode: "IN" },
    { id: 36, categoria: "Asia", testo: "The Israeli flag, with the Star of David, was created during the British Mandate.", opzioni: ["True", "False"], corretta: "False", isoCode: "IL" },
    { id: 37, categoria: "Asia", testo: "The cedar tree on the Lebanese flag symbolizes longevity and strength.", opzioni: ["True", "False"], corretta: "True", isoCode: "LB" },
    { id: 38, categoria: "Asia", testo: "The blue in the South Korean flag represents the balance between Yin and Yang.", opzioni: ["True", "False"], corretta: "False", isoCode: "KR" },
    { id: 39, categoria: "Asia", testo: "The Indonesian flag is identical to the Polish one, but with the colors inverted.", opzioni: ["True", "False"], corretta: "False", isoCode: "ID" },
    { id: 40, categoria: "Asia", testo: "The fourteen-point star on the Malaysian flag symbolizes its thirteen regions and the federal government.", opzioni: ["True", "False"], corretta: "True", isoCode: "MY" },
    { id: 41, categoria: "Asia", testo: "The red in the Vietnamese flag symbolizes the blood shed for independence.", opzioni: ["True", "False"], corretta: "True", isoCode: "VN" },
    { id: 42, categoria: "Asia", testo: "When the nation is at war, the Philippine flag is flown with the blue stripe on top.", opzioni: ["True", "False"], corretta: "False", isoCode: "PH" },
    { id: 43, categoria: "Asia", testo: "The sun in the Afghanistan flag is surrounded by a laurel wreath.", opzioni: ["True", "False"], corretta: "False", isoCode: "AF" },
    { id: 44, categoria: "Asia", testo: "The Iraqi flag features Kufic script that means 'God is Great'.", opzioni: ["True", "False"], corretta: "True", isoCode: "IQ" },
    { id: 45, categoria: "Asia", testo: "The three stars on the Syrian flag represent three-quarters of the country's population.", opzioni: ["True", "False"], corretta: "False", isoCode: "SY" },
    { id: 46, categoria: "Asia", testo: "The Nepal flag is the only one in the world that is not rectangular.", opzioni: ["True", "False"], corretta: "True", isoCode: "NP" },
    { id: 47, categoria: "Asia", testo: "The colors of the Indian flag (saffron, white, green) are known as Tiranga.", opzioni: ["True", "False"], corretta: "True", isoCode: "IN" },
    { id: 48, categoria: "Asia", testo: "The white in the Qatari flag represents peace and neutrality.", opzioni: ["True", "False"], corretta: "True", isoCode: "QA" },
    { id: 49, categoria: "Asia", testo: "The red in the Omani flag symbolizes the battles fought for independence.", opzioni: ["True", "False"], corretta: "True", isoCode: "OM" },
    { id: 50, categoria: "Asia", testo: "The North Korean flag is known as Inmin'gi.", opzioni: ["True", "False"], corretta: "True", isoCode: "KP" },
    { id: 51, categoria: "Asia", testo: "The Laos flag features a central white circle symbolizing the full moon over the Mekong River.", opzioni: ["True", "False"], corretta: "True", isoCode: "LA" },
    { id: 52, categoria: "Asia", testo: "The central element on the Kazakhstan flag is a golden camel.", opzioni: ["True", "False"], corretta: "False", isoCode: "KZ" },
    { id: 53, categoria: "Asia", testo: "The blue in the Uzbekistan flag represents the sky and water, sources of life.", opzioni: ["True", "False"], corretta: "True", isoCode: "UZ" },
    { id: 54, categoria: "Asia", testo: "The Turkmenistan flag features five carpet patterns (gül) symbolizing the country's five provinces.", opzioni: ["True", "False"], corretta: "True", isoCode: "TM" },
    { id: 55, categoria: "Asia", testo: "The blue circle in the Bangladesh flag represents water and unity.", opzioni: ["True", "False"], corretta: "False", isoCode: "BD" },
    { id: 56, categoria: "Asia", testo: "The Pakistan flag features a white stripe symbolizing religious minorities.", opzioni: ["True", "False"], corretta: "True", isoCode: "PK" },
    { id: 57, categoria: "Asia", testo: "The bird on the Egyptian flag is the Eagle of Saladin.", opzioni: ["True", "False"], corretta: "True", isoCode: "EG" },
    { id: 58, categoria: "Asia", testo: "The Jordanian flag has a black triangle on the hoist side.", opzioni: ["True", "False"], corretta: "False", isoCode: "JO" },
    { id: 59, categoria: "Asia", testo: "The Kuwaiti flag features Pan-Arab colors in a design of three horizontal stripes and a black trapezoid.", opzioni: ["True", "False"], corretta: "True", isoCode: "KW" },
    { id: 60, categoria: "Asia", testo: "The red in the Thailand flag represents the monarchy.", opzioni: ["True", "False"], corretta: "False", isoCode: "TH" },

    // ----------------------------------------------------------------------
    // AMERICA (30 QUESTIONS) - ID 61 to 90
    // ----------------------------------------------------------------------
    { id: 61, categoria: "America", testo: "The 50 stars on the flag of the United States represent the 50 capitals of the 50 states.", opzioni: ["True", "False"], corretta: "False", isoCode: "US" },
    { id: 62, categoria: "America", testo: "The Canadian flag features a fifteen-pointed maple leaf symbolizing its fifteen provinces.", opzioni: ["True", "False"], corretta: "False", isoCode: "CA" },
    { id: 63, categoria: "America", testo: "The blue in the Mexican flag symbolizes hope and the Catholic religion.", opzioni: ["True", "False"], corretta: "False", isoCode: "MX" },
    { id: 64, categoria: "America", testo: "The central coat of arms of the Mexican flag depicts an eagle devouring a snake on a cactus.", opzioni: ["True", "False"], corretta: "True", isoCode: "MX" },
    { id: 65, categoria: "America", testo: "The Brazilian flag features an inscription that in Portuguese means 'Order and Progress'.", opzioni: ["True", "False"], corretta: "True", isoCode: "BR" },
    { id: 66, categoria: "America", testo: "The sun (Sol de Mayo) on the Argentine flag symbolizes the country's declaration of independence.", opzioni: ["True", "False"], corretta: "True", isoCode: "AR" },
    { id: 67, categoria: "America", testo: "The red in the Chilean flag represents the blood shed for independence.", opzioni: ["True", "False"], corretta: "True", isoCode: "CL" },
    { id: 68, categoria: "America", testo: "The Colombian flag has a red band that is wider than the other two (yellow and blue).", opzioni: ["True", "False"], corretta: "False", isoCode: "CO" },
    { id: 69, categoria: "America", testo: "The blue and white on the Uruguayan flag represent the Caribbean Sea and the beaches.", opzioni: ["True", "False"], corretta: "False", isoCode: "UY" },
    { id: 70, categoria: "America", testo: "The Peruvian flag features a white stripe symbolizing peace and justice.", opzioni: ["True", "False"], corretta: "False", isoCode: "PE" },
    { id: 71, categoria: "America", testo: "The Bolivian flag has three horizontal stripes in the order of red, yellow, and green.", opzioni: ["True", "False"], corretta: "True", isoCode: "BO" },
    { id: 72, categoria: "America", testo: "The Paraguayan flag features the same emblem on the front and the back.", opzioni: ["True", "False"], corretta: "False", isoCode: "PY" },
    { id: 73, categoria: "America", testo: "The five stars on the Honduras flag represent the five nations of the United States of Central America.", opzioni: ["True", "False"], corretta: "True", isoCode: "HN" },
    { id: 74, categoria: "America", testo: "The blue in the Venezuelan flag symbolizes the seas and oceans surrounding the country.", opzioni: ["True", "False"], corretta: "False", isoCode: "VE" },
    { id: 75, categoria: "America", testo: "The triangle in the Cuban flag symbolizes parity and equality.", opzioni: ["True", "False"], corretta: "False", isoCode: "CU" },
    { id: 76, categoria: "America", testo: "The lion on the Jamaican flag symbolizes the strength and courage of the population.", opzioni: ["True", "False"], corretta: "False", isoCode: "JM" },
    { id: 77, categoria: "America", testo: "The Dominican Republic flag is the only one in the world to feature an open Bible.", opzioni: ["True", "False"], corretta: "True", isoCode: "DO" },
    { id: 78, categoria: "America", testo: "The two stars on the Panama flag symbolize the two political parties of the country.", opzioni: ["True", "False"], corretta: "True", isoCode: "PA" },
    { id: 79, categoria: "America", testo: "The red in the Nicaraguan flag symbolizes the blood shed for independence.", opzioni: ["True", "False"], corretta: "False", isoCode: "NI" },
    { id: 80, categoria: "America", testo: "The Haitian flag is a vertical bicolor of red and blue.", opzioni: ["True", "False"], corretta: "False", isoCode: "HT" },
    { id: 81, categoria: "America", testo: "The green in the Ecuadorian flag represents the wealth of its forests.", opzioni: ["True", "False"], corretta: "False", isoCode: "EC" },
    { id: 82, categoria: "America", testo: "The El Salvador flag features the national coat of arms with an equilateral triangle.", opzioni: ["True", "False"], corretta: "True", isoCode: "SV" },
    { id: 83, categoria: "America", testo: "The three blue stripes on the Guatemalan flag symbolize the two oceans surrounding the country.", opzioni: ["True", "False"], corretta: "False", isoCode: "GT" },
    { id: 84, categoria: "America", testo: "The Costa Rican flag has a wider red central band.", opzioni: ["True", "False"], corretta: "True", isoCode: "CR" },
    { id: 85, categoria: "America", testo: "The blue in the Puerto Rican flag (USA territory) symbolizes the sky.", opzioni: ["True", "False"], corretta: "False", isoCode: "PR" },
    { id: 86, categoria: "America", testo: "The Belize flag is the only national flag with 12 different colors.", opzioni: ["True", "False"], corretta: "True", isoCode: "BZ" },
    { id: 87, categoria: "America", testo: "The Mexican flag is a horizontal bicolor.", opzioni: ["True", "False"], corretta: "False", isoCode: "MX" },
    { id: 88, categoria: "America", testo: "The Venezuelan flag features eight stars symbolizing eight provinces.", opzioni: ["True", "False"], corretta: "True", isoCode: "VE" },
    { id: 89, categoria: "America", testo: "The Greenland flag (Danish territory) is identical to the Danish flag.", opzioni: ["True", "False"], corretta: "False", isoCode: "GL" },
    { id: 90, categoria: "America", testo: "The white in the Canadian flag symbolizes neutrality and peace.", opzioni: ["True", "False"], corretta: "False", isoCode: "CA" },

    // ----------------------------------------------------------------------
    // OTHER CONTINENTS (AFRICA & OCEANIA) (10 QUESTIONS) - ID 91 to 100
    // ----------------------------------------------------------------------
    { id: 91, categoria: "Africa & Oceania", testo: "The red, green, and blue in the South African flag symbolize the three main races of the country.", opzioni: ["True", "False"], corretta: "False", isoCode: "ZA" },
    { id: 92, categoria: "Africa & Oceania", testo: "The Ethiopian flag features a central pentagram symbolizing unity and the diversity of the people.", opzioni: ["True", "False"], corretta: "True", isoCode: "ET" },
    { id: 93, categoria: "Africa & Oceania", testo: "The star on the Australian flag is the North Star, used for navigation.", opzioni: ["True", "False"], corretta: "False", isoCode: "AU" },
    { id: 94, categoria: "Africa & Oceania", testo: "The New Zealand flag is identical to the Australian one, except for the number of stars.", opzioni: ["True", "False"], corretta: "False", isoCode: "NZ" },
    { id: 95, categoria: "Africa & Oceania", testo: "The Kenyan flag features a Masai shield symbolizing the defense of freedom.", opzioni: ["True", "False"], corretta: "True", isoCode: "KE" },
    { id: 96, categoria: "Africa & Oceania", testo: "The black in the Egyptian flag represents the dark past of oppression.", opzioni: ["True", "False"], corretta: "True", isoCode: "EG" },
    { id: 97, categoria: "Africa & Oceania", testo: "The red in the Chinese flag symbolizes joy and happiness.", opzioni: ["True", "False"], corretta: "False", isoCode: "CN" },
    { id: 98, categoria: "Africa & Oceania", testo: "The Tunisian flag is a red circle with a star and a crescent inside.", opzioni: ["True", "False"], corretta: "False", isoCode: "TN" },
    { id: 99, categoria: "Africa & Oceania", testo: "The blue of the Fiji flag symbolizes the Pacific Ocean.", opzioni: ["True", "False"], corretta: "True", isoCode: "FJ" },
    { id: 100, categoria: "Africa & Oceania", testo: "The Moroccan flag features a green six-pointed star called the 'Seal of Solomon'.", opzioni: ["True", "False"], corretta: "False", isoCode: "MA" }
];
